In [1]:
pip install wooldridge

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 33.5 MB/s eta 0:00:00


In [2]:
import numpy as np


In [3]:
import pandas as pd


In [4]:
import wooldridge as wd

In [25]:
wage = wd.data('wage1')[['wage','educ','exper']]
y = wage['wage'].to_numpy()
x = wage [['educ','exper']].to_numpy()

In [34]:
wage

wage  educ  exper
0     3.10    11      2
1     3.24    12     22
2     3.00    11      2
3     6.00     8     44
4     5.30    12      7
..     ...   ...    ...
521  15.00    16     14
522   2.27    10      2
523   4.67    15     13
524  11.56    16      5
525   3.50    14      5

[526 rows x 3 columns]

In [26]:
y

array([ 3.0999999 ,  3.24000001,  3.        ,  6.        ,  5.30000019,
        8.75      , 11.25      ,  5.        ,  3.5999999 , 18.18000031,
        6.25      ,  8.13000011,  8.77000046,  5.5       , 22.20000076,
       17.32999992,  7.5       , 10.63000011,  3.5999999 ,  4.5       ,
        6.88000011,  8.47999954,  6.32999992,  0.52999997,  6.        ,
        9.56000042,  7.78000021, 12.5       , 12.5       ,  3.25      ,
       13.        ,  4.5       ,  9.68000031,  5.        ,  4.67999983,
        4.26999998,  6.1500001 ,  3.50999999,  3.        ,  6.25      ,
        7.80999994, 10.        ,  4.5       ,  4.        ,  6.38000011,
       13.69999981,  1.66999996,  2.93000007,  3.6500001 ,  2.9000001 ,
        1.63      ,  8.60000038,  5.        ,  6.        ,  2.5       ,
        3.25      ,  3.4000001 , 10.        , 21.62999916,  4.38000011,
       11.71000004, 12.39000034,  6.25      ,  3.71000004,  7.78000021,
       19.97999954,  6.25      , 10.        ,  5.71000004,  2.  

In [27]:
x

array([[11,  2],
       [12, 22],
       [11,  2],
       ...,
       [15, 13],
       [16,  5],
       [14,  5]])

In [31]:
X = np.c_[np.ones(len(x)),x]
X

array([[ 1., 11.,  2.],
       [ 1., 12., 22.],
       [ 1., 11.,  2.],
       ...,
       [ 1., 15., 13.],
       [ 1., 16.,  5.],
       [ 1., 14.,  5.]])

In [32]:
betas= np.linalg.inv(X.T.dot(X)).dot(X.T.dot(y))


In [33]:
betas

array([-3.39053946,  0.64427208,  0.0700954 ])

In [42]:
y_estim= X.dot (betas)

In [44]:
error_estim = y - y_estim

In [46]:
sum(error_estim ** 2)
#numerador 

5548.159788779683

In [52]:
n,k = X.shape

In [49]:
n

526

In [53]:
k

3

In [55]:
sigma= 5548.159788779683/(n-k)

In [59]:
ee= np.diag(np.sqrt(sigma *  np.linalg.inv(X.T.dot(X))))

<ipython-input-59-5f49c04cbd1f>:1: RuntimeWarning: invalid value encountered in sqrt
  ee= np.diag(np.sqrt(sigma *  np.linalg.inv(X.T.dot(X))))


In [60]:
betas / ee

array([-4.423023  , 11.97396614,  6.38529107])

In [63]:
betas + (1.96*ee)
#limite superior

array([-1.88806992,  0.74973198,  0.09161156])

In [64]:
betas - (1.96*ee)
#limite inferior

array([-4.89300901,  0.53881218,  0.04857923])

los tres coeficientes son estadisticamente significativos 